// src/ai/flows/explain-alerts.ts
'use server';

/**
 * @fileOverview Provides AI-generated explanations for real-time alerts.
 *
 * - explainAlert - A function that generates explanations for alerts.
 * - ExplainAlertInput - The input type for the explainAlert function.
 * - ExplainAlertOutput - The return type for the explainAlert function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ExplainAlertInputSchema = z.object({
  alertType: z.string().describe('The type of alert (e.g., Presence Confirmed but Ticket Unverified, Persistent Likely Vacant seats).'),
  seatNumber: z.string().optional().describe('The seat number associated with the alert, if applicable.'),
  coachNumber: z.string().optional().describe('The coach number associated with the alert, if applicable.'),
  trainNumber: z.string().optional().describe('The train number associated with the alert, if applicable.'),
  additionalContext: z.string().optional().describe('Any additional context relevant to the alert.'),
});
export type ExplainAlertInput = z.infer<typeof ExplainAlertInputSchema>;

const ExplainAlertOutputSchema = z.object({
  explanation: z.string().describe('An AI-generated explanation of the alert, including the urgency and context.'),
});
export type ExplainAlertOutput = z.infer<typeof ExplainAlertOutputSchema>;

export async function explainAlert(input: ExplainAlertInput): Promise<ExplainAlertOutput> {
  return explainAlertFlow(input);
}

const explainAlertPrompt = ai.definePrompt({
  name: 'explainAlertPrompt',
  input: {schema: ExplainAlertInputSchema},
  output: {schema: ExplainAlertOutputSchema},
  prompt: `You are an AI assistant for railway personnel. Your task is to provide clear and concise explanations for various alerts generated by the system.

  Given the following alert information, generate a human-readable explanation that helps the TTE (Travelling Ticket Examiner) understand the urgency and context behind the alert. The explanation should be tailored to assist in making informed decisions and prioritizing actions effectively.

  Alert Type: {{{alertType}}}
  Seat Number: {{{seatNumber}}}
  Coach Number: {{{coachNumber}}}
  Train Number: {{{trainNumber}}}
  Additional Context: {{{additionalContext}}}

  Explanation:`,
});

const explainAlertFlow = ai.defineFlow(
  {
    name: 'explainAlertFlow',
    inputSchema: ExplainAlertInputSchema,
    outputSchema: ExplainAlertOutputSchema,
  },
  async input => {
    const {output} = await explainAlertPrompt(input);
    return output!;
  }
);
